### ISSUE TITLE
Listener Race Condition

### ISSUE THREAD

**Issue by night** [Fieldscope/flux-hooks#1]
This is a neat little util. I did notice a slight race condition caused by the fact that `useEffect` runs *after* render, so if a store you're watching changes before the listener is attached, the component will never receive the change. This could probably be resolved by dispatching to the reducer when the listener is added.

**Comment by patelnav** [comment]
Surprised that a store could change between initializing the reducer till the first render. I assumed it'd almost be synchronous, although that's probably a bad assumption to make.

Did you actually run into this race condition?

**Comment by patelnav** [comment]
@night: Give it a quick once-over

https://github.com/Fieldscope/flux-hooks/pull/2

**Comment by night** [comment]
> Did you actually run into this race condition?

locally I sporadically was, but that stopped when I added the additional dispatch I suggested

> Give it a quick once-over

changes look fine to me
